name: Docker

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4.1.4
      
    - name: Build Docker Image
      run: docker build ./ --file ./swift.Dockerfile --tag amd64/calculate_engine_swift:latest