name: Swift

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  schedule:
  - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.2
    
    - name: Dependency Graph
      run: swift package -v show-dependencies